<a href="https://colab.research.google.com/github/Shambhavi-Gupta/DS_Pandas_Creating-Dataframe-Objects/blob/master/DS_Pandas_Creating_Dataframe_Objects_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

#**Creating dataframe objects**

In [ ]:
arr = np.random.randint(0, 10, (5, 3))

In [ ]:
arr

array([[4, 6, 9],
       [7, 8, 5],
       [5, 9, 4],
       [2, 8, 5],
       [1, 8, 0]])

In [ ]:
df = pd.DataFrame(arr)

In [ ]:
df

0  1  2
0  4  6  9
1  7  8  5
2  5  9  4
3  2  8  5
4  1  8  0

In [ ]:
df.values

array([[4, 6, 9],
       [7, 8, 5],
       [5, 9, 4],
       [2, 8, 5],
       [1, 8, 0]])

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
for c in df.columns:
    print(c)

0
1
2


In [ ]:
df.values[0]

array([4, 6, 9])

In [ ]:
df.index = ['R1', 'R2', 'R3', 'R4', 'R5']
df.columns=['C1', 'C2' ,'C3']

In [ ]:
df

C1  C2  C3
R1   4   6   9
R2   7   8   5
R3   5   9   4
R4   2   8   5
R5   1   8   0

In [ ]:
df.loc['R3', 'C2']

9

In [ ]:
df.iloc[2, 1]

9

In [ ]:
df.iloc[2:4 , 1:3]

C2  C3
R3   9   4
R4   8   5

In [ ]:
type(df.iloc[2:4 , 1:3])

pandas.core.frame.DataFrame

In [ ]:
df.loc['R3':'R5', 'C2':'C3']

C2  C3
R3   9   4
R4   8   5
R5   8   0

In [ ]:
df.iloc[0]

C1    4
C2    6
C3    9
Name: R1, dtype: int64

In [ ]:
type(df.iloc[0])

pandas.core.series.Series

In [ ]:
df.iloc[:, 0]

R1    4
R2    7
R3    5
R4    2
R5    1
Name: C1, dtype: int64

In [ ]:
df.shape

(5, 3)

In [ ]:
df.T

R1  R2  R3  R4  R5
C1   4   7   5   2   1
C2   6   8   9   8   8
C3   9   5   4   5   0

Task on creating dataframes

In [ ]:
def create_df(nRows, nCols, maxrand=10):
    arr = np.random.randint(0, maxrand, (nRows, nCols))
    df = pd.DataFrame(arr)
    df.index = ['R' + str(x) for x in np.arange(1, nRows +1)]
    df.columns= ['R' + str(x) for x in np.arange(1, nCols +1)]
    return df

In [ ]:
create_df(5,3)

R1  R2  R3
R1   6   5   3
R2   9   3   0
R3   6   6   2
R4   0   9   2
R5   1   5   7

In [ ]:
create_df(2, 5)

R1  R2  R3  R4  R5
R1   9   0   4   1   8
R2   0   5   0   0   2

In [ ]:
mass = pd.Series([0.33 , 4.87 , 5.97 , 0.642 , 1898 , 568 , 86.8 , 102 , 0.0146],
                 index = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])
diameter = pd.Series([4879, 12104, 12756, 3475, 6792, 142984, 120536, 51118, 49528, 2370],
                     index =['Mercury', 'Venus', 'Earth','Moon', 'Mars', 'Jupiter', 'Saturn','Uranus','Neptune', 'Pluto'])

In [ ]:
mass

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Pluto         0.0146
dtype: float64

In [ ]:
diameter

Mercury      4879
Venus       12104
Earth       12756
Moon         3475
Mars         6792
Jupiter    142984
Saturn     120536
Uranus      51118
Neptune     49528
Pluto        2370
dtype: int64

In [ ]:
df = pd.DataFrame({'Mass':mass , 'Diameter':diameter})

In [ ]:
df

Mass  Diameter
Earth       5.9700     12756
Jupiter  1898.0000    142984
Mars        0.6420      6792
Mercury     0.3300      4879
Moon           NaN      3475
Neptune   102.0000     49528
Pluto       0.0146      2370
Saturn    568.0000    120536
Uranus     86.8000     51118
Venus       4.8700     12104

In [ ]:
df['Mass']

Earth         5.9700
Jupiter    1898.0000
Mars          0.6420
Mercury       0.3300
Moon             NaN
Neptune     102.0000
Pluto         0.0146
Saturn      568.0000
Uranus       86.8000
Venus         4.8700
Name: Mass, dtype: float64

In [ ]:
df['Diameter']

Earth       12756
Jupiter    142984
Mars         6792
Mercury      4879
Moon         3475
Neptune     49528
Pluto        2370
Saturn     120536
Uranus      51118
Venus       12104
Name: Diameter, dtype: int64

In [ ]:
df['Mass']['Earth']

5.97

In [ ]:
df.Mass.Earth

5.97

In [ ]:
df['pop'] = 0

In [ ]:
df

Mass  Diameter  pop
Earth       5.9700     12756    0
Jupiter  1898.0000    142984    0
Mars        0.6420      6792    0
Mercury     0.3300      4879    0
Moon           NaN      3475    0
Neptune   102.0000     49528    0
Pluto       0.0146      2370    0
Saturn    568.0000    120536    0
Uranus     86.8000     51118    0
Venus       4.8700     12104    0

In [ ]:
df['pop']['Earth'] = 8000000000 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df

Mass  Diameter         pop
Earth       5.9700     12756  8000000000
Jupiter  1898.0000    142984           0
Mars        0.6420      6792           0
Mercury     0.3300      4879           0
Moon           NaN      3475           0
Neptune   102.0000     49528           0
Pluto       0.0146      2370           0
Saturn    568.0000    120536           0
Uranus     86.8000     51118           0
Venus       4.8700     12104           0

In [ ]:
df['Mass'] is df.Mass

True

In [ ]:
df['pop'] is df.pop

False